version: '3'
services:
  nginx:
    image: hatiolab/operato-nginx:latest
    ports:
      - ${HostPort}:80
    depends_on:
      - app
  app:
    build: .
    container_name: operato-board
    image: hatiolab/operato-board:latest
    privileged: true
    volumes:
      - ./logs:/app/logs
      - ./attachments:/app/attachments
      - ./config.production.js:/app/config.production.js
      - ./license.json:/app/license.json
    ports:
      - 4000:3000
    depends_on:
      - postgres
      - mosquitto
      - scheduler
    restart: always
  
  postgres:
    image: postgres:13.2
    container_name: db-operato-board
    environment:
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - '55432:5432'
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    ports:
      - 1883:1883
      - 9001:9001

  scheduler:
    image: hatiolab/schevt-mgr:latest
    container_name: scheduler
    volumes:
      - ./scheduler-config.yaml:/app/config.yaml
      - ./evt_queue:/app/evt_queue
    ports:
      - '9902:9902'
